version: "3.4"

services:
  main:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - QUICKAUTH_URL=https://anr.alles.cc/account/quickauth
      - JWT_SECRET=
      - DB_HOST=
      - DB_NAME=
      - DB_USERNAME=
      - DB_PASSWORD=
      - VERDACCIO_LOGIN=https://anr.alles.cc/-/verdaccio/login